version: "3.9"

networks:
  001_basic_curd_global_network:
    external: true

services:
  001_basic_curd_node_app_service:
    image: node:latest
    container_name: 001_basic_curd_node_app_container
    working_dir: /app
    command: sh -c "npm install && npm run tsc"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    networks:
      - 001_basic_curd_global_network
