version: "3.8"

networks:
  task_manager_app_network:
    external: true

services:
  node-app:
    container_name: node-container
    image: node:latest
    command: tail -f /dev/null
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - task_manager_app_network
