version: "3.9"

networks:
  001_basic_curd_node_network:
    driver: bridge
    name: 001_basic_curd_node_network

services:
  001_basic_curd_node_app_service:
    image: node:latest
    container_name: 001_basic_curd_node_app_container
    working_dir: /app
    volumes:
      - ./:/app        # bind mount local code
    command: tail -f /dev/null   # keep container running (replace with npm start if needed)
    networks:
      - 001_basic_curd_node_network
