networks:
  001_basic_curd_global_network:
    name: 001_basic_curd_global_network
    driver: bridge

services:
  network-keeper:
    image: nginx:alpine   # lightweight container
    container_name: network_keeper
    networks:
      - 001_basic_curd_global_network
    command: ["tail", "-f", "/dev/null"] # keep it alive doing nothing
