# Use the official Node.js image from Docker Hub
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Node.js script into the container
COPY . .

# Run the Node.js script
CMD ["node", "keep-alive.js"]